language: elixir
sudo: false
matrix:
  include:
  - elixir: 1.7.2
    otp_release: 21.0
  - elixir: 1.7.2
    otp_release: 20.3.1
  - elixir: 1.6.6
    otp_release: 19.3
  - elixir: 1.5.3
    otp_release: 18.3
  - elixir: 1.5.3
    otp_release: 17.5
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
    - an.leopardi@gmail.com
