language: elixir

services:
  - docker

otp_release: '21.3'
elixir: '1.8'

env:
  - DOCKER_COMPOSE_VERSION=1.22.0

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test
      script:
        - docker-compose up --detach
        - mix test --trace --include proxy

    - otp_release: '21.2'
      elixir: '1.8'

    - otp_release: '20.3.1'
      elixir: '1.7'

    - otp_release: '19.3'
      elixir: '1.6'

    - otp_release: '18.3'
      elixir: '1.5'

    - stage: check formatted
      script: mix format --check-formatted
      sudo: false
      before_install: skip

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose build
